# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\barankrky\CodingWorkspace\passwordGenerator\passwordGenerator\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(358, 126)
        self.passOutput = QtWidgets.QLineEdit(Form)
        self.passOutput.setGeometry(QtCore.QRect(90, 20, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.passOutput.setFont(font)
        self.passOutput.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.passOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.passOutput.setReadOnly(True)
        self.passOutput.setClearButtonEnabled(False)
        self.passOutput.setObjectName("passOutput")
        self.generateButton = QtWidgets.QCommandLinkButton(Form)
        self.generateButton.setGeometry(QtCore.QRect(140, 70, 111, 41))
        self.generateButton.setObjectName("generateButton")
        self.passlbl = QtWidgets.QLabel(Form)
        self.passlbl.setGeometry(QtCore.QRect(20, 20, 61, 31))
        self.passlbl.setObjectName("passlbl")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.passOutput.setText(_translate("Form", "Generated Password"))
        self.generateButton.setText(_translate("Form", "Generate"))
        self.passlbl.setText(_translate("Form", "Password :"))
